---
- hosts: server
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install httpd on linux
      action: yum name=httpd state=installed
    - name: copy file
      copy:
        src: test.txt
        dest: /var                
