kind: Pod
apiVersion: v1
metadata:
  namespace: pradeep
  name: pod
  labels:
     name: pod
spec:
  containers:
  - name: pod1
    image:  pradeepcoeb/javaimage:52
    ports:
    - containerPort: 8080
